name: Deploy Static Site

on:
  push:
    branches:
      - restart2020

jobs:
  deploy:
    runs-on: Ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn build
      - name: Generate staic site
        run: yarn render
      - name: Upload to S3
        run: |
          aws s3 cp --recursive --exclude "*" --include "*.js" --include "*.css" --include "*.jpg" --include "*.png" --cache-control "max-age=31536000" out s3://${{ secrets.BUCKET_ARN}}
          aws s3 cp --recursive --include "*" --exclude "*.js" --exclude "*.css" --exclude "*.jpg" --exclude "*.png" --cache-control "max-age=0" out s3://${{ secrets.BUCKET_ARN}}
          # aws s3 cp --recursive --exclude "*" --include "*.html" --include "*.json" --include "*.xml" --include "*.txt" --cache-control "max-age=0" out s3://${{ secrets.BUCKET_ARN}}
