name: Deploy Static Site

on:
  push:
    branches:
      - restart2020

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn build
      - name: Upload to S3
        run: |
          aws s3 cp --recursive --exclude "*" --include "*.js" --include "*.css" --include "*.jpg" --include "*.png" --cache-control "max-age=31536000" dist s3://${{ secrets.BUCKET_ARN}}
          aws s3 cp --recursive --include "*" --exclude "*.js" --exclude "*.css" --exclude "*.jpg" --exclude "*.png" --cache-control "max-age=0" dist s3://${{ secrets.BUCKET_ARN}}
