name: Deploy Static Site

on:
  push:
    branches:
      - main
permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn build
      - name: Upload to S3
        run: |
          aws s3 cp --recursive --exclude "*" --include "*.js" --include "*.css" --include "*.jpg" --include "*.png" --cache-control "max-age=31536000" dist s3://${{ secrets.BUCKET_ARN}}
          aws s3 cp --recursive --include "*" --exclude "*.js" --exclude "*.css" --exclude "*.jpg" --exclude "*.png" --cache-control "max-age=0" dist s3://${{ secrets.BUCKET_ARN}}
          # aws s3 cp --website-redirect "/about.html" --cache-control "max-age=900" 0byte.txt s3://${{ secrets.BUCKET_ARN}}/test-redirect.html
      - name: Success notification
        if: success()
        run: |
          curl -X POST \
                -H 'Content-Type: application/json' \
                -d '{"chat_id": "859819541", "text": "\u2705 Deployment succeeded", "disable_notification": true}' \
                ${{ secrets.TELEGRAM_URL }}/sendMessage
      - name: Failure notification
        if: failure()
        run: |
          curl -X POST \
                -H 'Content-Type: application/json' \
                -d '{"chat_id": "859819541", "text": "\u26a0 - Deployment failed", "disable_notification": false}' \
                ${{ secrets.TELEGRAM_URL }}/sendMessage
      - name: Site Tests
        continue-on-error: true
        working-directory: page-tests
        run: |
          yarn
          yarn test
