name: Healthcheck
on:
  schedule:
    - cron: '43 7-19 * * *'

jobs:
  healthcheck:
    runs-on: ubuntu-22.04
    steps:
      - run: |
          curl -sSf https://bdadam.com/ > /dev/null
          curl -sSf https://bdadam.com/about.html > /dev/null
          curl -sSf https://bdadam.com/blog/displaying-icons-with-custom-elements.html > /dev/null
          curl -sSf https://bdadam.com/sitemap.xml > /dev/null
          curl -sSf https://bdadam.com/rss.xml > /dev/null
