name: Healthcheck
on:
  schedule:
    - cron: '43 7,10,13,16,19 * * *'
  workflow_run:
    workflows: ['Deploy Static Site']
    types:
      - completed

jobs:
  healthcheck:
    runs-on: ubuntu-22.04
    steps:
      - run: |
          curl -sSf https://bdadam.com/ > /dev/null
          curl -sSf https://bdadam.com/about.html > /dev/null
          curl -sSf https://bdadam.com/blog/displaying-icons-with-custom-elements.html > /dev/null
          curl -sSf https://bdadam.com/sitemap.xml > /dev/null
          curl -sSf https://bdadam.com/rss.xml > /dev/null
      - name: Success notification
        if: success()
        run: |
          curl -X POST \
                -H 'Content-Type: application/json' \
                -d '{"chat_id": "859819541", "text": "\u2b06 - OK", "disable_notification": true}' \
                ${{ secrets.TELEGRAM_URL }}/sendMessage
      - name: Failure notification
        if: failure()
        run: |
          curl -X POST \
                -H 'Content-Type: application/json' \
                -d '{"chat_id": "859819541", "text": "\u26a0 - ERROR", "disable_notification": false}' \
                ${{ secrets.TELEGRAM_URL }}/sendMessage
